<?php
/**
 * PSR16 Cache Adapter
 *
 * Copyright (c) 2017 http://pudelek.org.pl
 *
 * @license MIT License (MIT)
 *
 * For the full copyright and license information, please view source file
 * that is bundled with this package in the file LICENSE
 *
 * @author Marcin Pudełek <marcin@pudelek.org.pl>
 */


namespace mrcnpdlk\Psr16Cache;

class TestCase extends \PHPUnit\Framework\TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
